#!/usr/bin/env python3
"""
ytb_dl_playlist_audio_first.py
Reads a Spotify-exported CSV and downloads YouTube audio as MP3.
Prefers audio-only uploads (Official Audio / - Topic / auto-generated) and falls back to videos.
Requires: Python 3.9+, ffmpeg in PATH, pip install yt-dlp
"""

import argparse
import csv
import os
import sys
import pathlib
import re
from yt_dlp import YoutubeDL

SPOTIFY_TITLE_COL = "Track Name"
SPOTIFY_ARTIST_COL = "Artist Name(s)"

AUDIO_POSITIVE_PATTERNS = [
	r"\bofficial audio\b",
	r"\baudio\b",
	r"\bfull audio\b",
	r"\blyrics\b",
	r"\blyrics video\b",
]
AUDIO_NEGATIVE_PATTERNS = [
	r"\bvisualizer\b",
	r"\bmusic video\b",
	r"\bofficial video\b",
	r"\bmv\b",
	r"\bperformance\b",
	r"\blive\b",
	r"\bremix\b",
	r"\bsped up\b",
	r"\bslowed\b",
]

def ensure_dir(p: str) -> None:
	pathlib.Path(p).mkdir(parents=True, exist_ok=True)

def parse_csv(csv_path: str):
	pairs = []

	with open(csv_path, newline="", encoding="utf-8") as f:
		# Try headered CSV first
		sniff = f.read(4096)
		f.seek(0)
		dialect = csv.Sniffer().sniff(sniff) if sniff else csv.excel
		reader = csv.DictReader(f, dialect=dialect)

		if reader.fieldnames and (SPOTIFY_TITLE_COL in reader.fieldnames):
			for row in reader:
					title = (row.get(SPOTIFY_TITLE_COL) or "").strip()
					artist_raw = (row.get(SPOTIFY_ARTIST_COL) or "").strip()
					if not title:
						continue
					# Collapse "A, B, C" → "A B C"
					artist = " ".join(a.strip() for a in artist_raw.split(",") if a.strip())
					pairs.append((title, artist))
			return pairs

	# Fallback to simple CSV without headers: first two columns → title, artist
	with open(csv_path, newline="", encoding="utf-8") as f:
		reader = csv.reader(f)
		for row in reader:
			if not row:
					continue
			title = (row[0] or "").strip()
			artist = (row[1] or "").strip() if len(row) > 1 else ""
			if title:
					pairs.append((title, artist))
	return pairs

def build_ydl_opts(out_dir: str, search_count: int = 15, sleep_interval: int = 0):
	opts = {
		"quiet": True,
		"noprogress": True,
		"nocheckcertificate": True,
		"ignoreerrors": True,
		"noplaylist": True,
		# search more candidates so we can choose the best "audio-only" one
		"default_search": f"ytsearch{search_count}",
		"outtmpl": os.path.join(out_dir, "%(title)s.%(ext)s"),
		"postprocessors": [
			{"key": "FFmpegExtractAudio", "preferredcodec": "mp3", "preferredquality": "0"}
		],
		"format": "bestaudio/best",
		# We'll search without downloading first, then download the chosen URL
		"skip_download": True,
	}
	if sleep_interval > 0:
		opts["sleep_interval"] = sleep_interval
	return opts

def _norm(s: str) -> str:
	return re.sub(r"\s+", " ", (s or "").lower()).strip()

def _contains_all(hay: str, *needles: str) -> bool:
	return all(_norm(n) in _norm(hay) for n in needles if n)

def score_candidate(e, title: str, artist: str) -> int:
	"""
	Heuristic scorer that prioritizes audio-only / Topic / auto-generated uploads,
	and penalizes lyric/visualizer/music video content.
	"""
	score = 0
	etitle = _norm(e.get("title") or "")
	uploader = _norm(e.get("uploader") or e.get("channel") or "")
	desc = _norm(e.get("description") or "")
	categories = [c.lower() for c in (e.get("categories") or [])]

	# Strong signals of audio-only
	if " - topic" in uploader:
		score += 60
	if "provided to youtube by" in desc or "auto-generated by youtube" in desc:
		score += 45
	# Title-based positives
	for pat in AUDIO_POSITIVE_PATTERNS:
		if re.search(pat, etitle):
			score += 30
			break

	# Title-based negatives
	for pat in AUDIO_NEGATIVE_PATTERNS:
		if re.search(pat, etitle):
			score -= 35
			break

	# Category hint
	if "music" in categories:
		score += 5

	# Basic relevance to query
	if _contains_all(etitle, title):
		score += 20
	if artist and (_contains_all(etitle, artist) or artist in uploader):
		score += 15

	# Very short or very long durations can be weird (like shorts or full albums)
	dur = e.get("duration")
	if isinstance(dur, (int, float)) and dur:
		if dur < 60:
			score -= 20
		elif dur > 15 * 60:  # likely not a single track
			score -= 10

	return score

def choose_best(info, title: str, artist: str):
	"""
	From a ytsearch result (dict with 'entries'), pick the best candidate.
	Prefer audio-only; otherwise fall back to the first non-null entry.
	"""
	entries = [e for e in (info.get("entries") or []) if e]
	if not entries:
		return None

	# Score and sort
	ranked = sorted(
		((score_candidate(e, title, artist), e) for e in entries),
		key=lambda t: t[0],
		reverse=True,
	)
	best_score, best_entry = ranked[0]

	# Define a threshold that means "confident audio-only-ish"
	AUDIO_CONFIDENCE_THRESHOLD = 35

	if best_score >= AUDIO_CONFIDENCE_THRESHOLD:
		return best_entry

	# Otherwise, fallback to the first result (ytsearch is relevance-sorted)
	return entries[0]

def main():
	ap = argparse.ArgumentParser(description="Lookup songs on YouTube and download as MP3 (audio-first).")
	ap.add_argument("csv", help="Input CSV (Spotify export or title,artist)")
	ap.add_argument("-o", "--out-dir", required=True, help="Output directory for MP3 files")
	ap.add_argument("--search-count", type=int, default=15, help="How many YouTube results to scan per song (default: 15)")
	ap.add_argument("-t", "--sleep-interval", type=int, default=0, help="Sleep interval (seconds) between downloads to avoid rate limiting (default: 0)")
	args = ap.parse_args()

	inp = args.csv.strip()
	# If the input looks like a direct URL, download it directly instead of reading a CSV
	

	if inp.startswith(("http://", "https://")):
		out_dir = os.path.abspath(args.out_dir)
		ensure_dir(out_dir)

		ydl_opts = build_ydl_opts(out_dir, search_count=max(5, min(args.search_count, 50)), sleep_interval=args.sleep_interval)
		ydl_opts["ffmpeg_location"] = os.path.expanduser("~/bin/ffmpeg")
		ydl_opts["skip_download"] = False  # directly download
		with YoutubeDL(ydl_opts) as ydl:
			print(f"Downloading direct link: {inp}")
			ydl.download([inp])
		return

	csv_path = os.path.abspath(args.csv)
	if not os.path.isfile(csv_path):
		print("ERROR: Input CSV not found", file=sys.stderr)
		sys.exit(1)

	base = os.path.splitext(os.path.basename(csv_path))[0]
	out_dir = os.path.abspath(args.out_dir)
	ensure_dir(out_dir)

	rows = parse_csv(csv_path)
	if not rows:
		print("ERROR: No rows parsed from CSV", file=sys.stderr)
		sys.exit(1)

	print(f"Parsed {len(rows)} tracks")
	print(f"Output directory: {out_dir}")

	failures = []
	succeeded = 0

	ydl_opts = build_ydl_opts(out_dir, search_count=max(5, min(args.search_count, 50)), sleep_interval=args.sleep_interval)
	# ydl_opts["ffmpeg_location"] = os.path.expanduser("~/bin/ffmpeg")
	# Try to locate an ffmpeg we can use without sudo
	ffprobe_candidates = []
	try:
		import imageio_ffmpeg  # pip install --user imageio-ffmpeg
		ffmpeg_bin = imageio_ffmpeg.get_ffmpeg_exe()
	except Exception:
		ffmpeg_bin = None

	# Let an environment variable override if you set one (e.g., export FFMPEG=~/bin/ffmpeg)
	ffmpeg_bin = os.environ.get("FFMPEG", ffmpeg_bin) or os.path.expanduser("~/bin/ffmpeg")

	if os.path.isfile(ffmpeg_bin) and os.access(ffmpeg_bin, os.X_OK):
		ydl_opts["ffmpeg_location"] = ffmpeg_bin
	else:
	# if not found, we still run; but MP3 extraction will fail unless you use Option C
		pass
	with YoutubeDL(ydl_opts) as ydl:
		for idx, (title, artist) in enumerate(rows, 1):
			# Guard against raw Spotify links sneaking in as "title"
			if title.startswith(("spotify:", "https://open.spotify.com")):
				failures.append((title, artist, "spotify_url_not_supported"))
				print(f"[{idx}/{len(rows)}] SKIP: Spotify URL not supported → {title}")
				continue

			query = f"ytsearch{ydl_opts['default_search'].split('ytsearch')[-1]}:{title} {artist}".strip()
			print(f"[{idx}/{len(rows)}] Searching: {title} — {artist}")

			try:
				# 1) Search (no download)
				info = ydl.extract_info(query, download=False)
				if info is None:
					failures.append((title, artist, "no_result"))
					print("    NOT FOUND")
					continue

				chosen = info
				if "entries" in info:
					chosen = choose_best(info, title, artist)

				if not chosen:
					failures.append((title, artist, "no_result"))
					print("    NOT FOUND")
					continue

				# 2) Download the chosen candidate's URL
				chosen_url = chosen.get("webpage_url") or chosen.get("url")
				disp = chosen.get("title") or title
				print(f"    SELECTED: {disp}  (uploader: {chosen.get('uploader')})")
				# Temporarily enable download just for this item
				ydl.params["skip_download"] = False
				ydl.download([chosen_url])
				ydl.params["skip_download"] = True

				succeeded += 1
				print(f"    DOWNLOADED: {disp}")
			except Exception as e:
				failures.append((title, artist, str(e)[:200]))
				print(f"    ERROR: {str(e)[:200]}")

	print(f"\nDone. Succeeded: {succeeded} / {len(rows)}")
	if failures:
		nf = os.path.join(out_dir, f"{base}_not_found.csv")
		with open(nf, "w", newline="", encoding="utf-8") as f:
			w = csv.writer(f)
			w.writerow(["title", "artist", "reason"])
			w.writerows(failures)
		print(f"Not found or failed: {len(failures)} → {nf}")

if __name__ == "__main__":
	main()
